In [4]:
import torch
import numpy as np

a=np.array([1,2])
a=torch.asarray(a)
a

tensor([1, 2], dtype=torch.int32)

In [5]:
a=torch.arange(0,4,1)
a

tensor([0, 1, 2, 3])

In [6]:
a=torch.linspace(0,4,4)
a

tensor([0.0000, 1.3333, 2.6667, 4.0000])

In [7]:
a.argwhere()

tensor([[1],
        [2],
        [3]])

In [8]:
x = torch.randn(3, 4)
indices = torch.tensor([0, 2])
torch.index_select(x, 0, indices)
x>0.5

tensor([[ True, False, False, False],
        [ True, False,  True,  True],
        [False, False,  True, False]])

In [9]:
x=torch.arange(8)
x.split(3)

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7]))

In [14]:
x.copy_(torch.Tensor([1,2,3,4,5,6,7,8]))

tensor([1, 2, 3, 4, 5, 6, 7, 8])